"""add field unit_price into table OrderDetail

Revision ID: 277cb2f79bf1
Revises: df962931e507
Create Date: 2024-12-21 16:53:56.182169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277cb2f79bf1'
down_revision = 'df962931e507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###
