"""remove field unit_price

Revision ID: 3da4d85a718a
Revises: 4e9201b66ad7
Create Date: 2024-12-11 14:31:24.132651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3da4d85a718a'
down_revision = '4e9201b66ad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', mysql.FLOAT(), nullable=False))

    # ### end Alembic commands ###
