"""allow null at field customer_id in table order

Revision ID: 61dda924d869
Revises: 3da4d85a718a
Create Date: 2024-12-15 09:26:08.332467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61dda924d869'
down_revision = '3da4d85a718a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
