"""add pages field to table book

Revision ID: 6a01c1577edf
Revises: 7e3d60274a98
Create Date: 2024-12-09 16:07:13.695239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a01c1577edf'
down_revision = '7e3d60274a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Pages', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('Pages')

    # ### end Alembic commands ###
